'use strict';

/* eslint max-len: ["error", 1000]*/
exports.seed = function(knex) {
  return knex('flowers').del()
    .then(() => {
      return knex('flowers').insert(
      [
       {
         "name": "Anniversary Bouquet",
         "code": "AVB",
         "price": 54.95,
         "description": "The Anniversary Bouquet is a gorgeous way to celebrate your sweet affection for the love of your life on your special day. Showcasing rich red roses, brilliant pink Asiatic lilies, pale pink stock and a variety of lush greens, this beautiful bouquet is presented in a clear t glass vase for a classic look of sophistication and elegance.",
         "dimensions": "13\"w x 15\"h",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/AVB_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/AVB_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=AVB&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=AVB&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 1,
         "love": 1,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Vase Arrangements"
       },
       {
         "name": "The Holiday Happiness Bouquet",
         "code": "B10-4355",
         "price": 47.95,
         "description": "The Holiday Happiness Bouquet",
         "dimensions": "13\"H x 10\"W",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B10-4355_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B10-4355_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B10-4355&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B10-4355&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Centerpieces"
       },
       {
         "name": "Celebration of the Season Centerpiece",
         "code": "B10-4368",
         "price": 74.95,
         "description": "The Celebration of the Season Centerpiece is a grand display of holiday elegance. Red roses and spray roses pop against a backdrop of assorted holiday greens and variegated holly that beautifully encircle three red taper candles. Accented with gold pinecones and gold metallic brocade ribbon this centerpiece creates a warm and enchanting glow to benefit their holiday festivities.",
         "dimensions": "7\"H x 14\"W",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B10-4368_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B10-4368_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B10-4368&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B10-4368&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Centerpieces"
       },
       {
         "name": "The Spirit of the Season Bouquet",
         "code": "B10-4787",
         "price": 49.95,
         "description": "The Spirit of the Season Bouquet bursts with beauty and cheer to dazzle your special recipient with its holiday beauty. Brilliant red spray roses and mini carnations are brought together with burgundy mini carnations, red hypericum berries and assorted holiday greens in a clear glass vase accented with a thick red designer ribbon to create a special sentiment of seasonal wishes and caring kindness",
         "dimensions": "14\"H x 9\"W",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B10-4787_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B10-4787_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B10-4787&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B10-4787&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Centerpieces"
       },
       {
         "name": "The Winter Elegance Bouquet",
         "code": "B12-4421",
         "price": 69.95,
         "description": "The Winter Elegance Bouquet offers warm wishes and bright sentiments for a wonderful holiday season! Rich red roses and peppermint carnations are delicately arranged amongst holiday greens to create a festive display. Arriving in a clear glass bubble bowl and accented with a red and white plaid ribbon, this arrangement is full of seasonal sophistication.",
         "dimensions": "7\"H x 14\"W",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B12-4421_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B12-4421_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B12-4421&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B12-4421&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Centerpieces"
       },
       {
         "name": " Red Poinsettia Basket (Small)  ",
         "code": "B13-3601",
         "price": 49.95,
         "description": "The traditional holiday blooming plant, a Christmas Poinsettia, with its dark leaves and deep red flowers is the perfect gift for family and friends.",
         "dimensions": "6\" pot",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B11-3601_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B11-3601_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B13-3601&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B13-3601&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Plants"
       },
       {
         "name": " Red Poinsettia Basket (Large)  ",
         "code": "B13-3602",
         "price": 74.95,
         "description": "The traditional holiday blooming plant, a Christmas Poinsettia, with its dark leaves and deep red flowers is the perfect gift for family and friends.",
         "dimensions": "8\" pot",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B11-3602_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B11-3602_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B13-3602&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B13-3602&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Plants"
       },
       {
         "name": "The Holiday Enchantment Bouquet",
         "code": "B13-4834",
         "price": 54.95,
         "description": "The Holiday Enchantment Bouquet is blooming with bright seasonal cheer to bring Christmas joy to your special recipient. Rich red roses are surrounded by white Peruvian lilies, variegated holly and assorted holiday greens perfectly arranged in a clear glass vase tied at the neck with a candy cane striped ribbon to create a fantastic holiday look.",
         "dimensions": "16\"H x13\"W",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B13-4834_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B13-4834_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B13-4834&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B13-4834&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Centerpieces"
       },
       {
         "name": "The Merry & Bright Bouquet",
         "code": "B14-4356",
         "price": 49.95,
         "description": "The Merry & Bright Bouquet is a charming display of seasonal cheer. Vibrant red roses, white spray roses, red hypericum berries and assorted holiday greens create a stunning look with green glass balls and green taffeta ribbon nestled within the arrangement. Arranged in a red glass cube vase, this bouquet is guaranteed to make their holiday both merry and bright.",
         "dimensions": "11\"H x 10\"W",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B14-4356_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B14-4356_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B14-4356&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B14-4356&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Centerpieces"
       },
       {
         "name": "Candy Cane Lane Bouquet",
         "code": "B14-4426",
         "price": 59.95,
         "description": "The Candy Cane Lane Bouquet is a festive and fun way to celebrate the arrival of the holiday season. Bright red roses and mini carnations are offset by snowy white chrysanthemums and assorted holiday greens, beautifully arranged in a white wash basket and accented with 3 candy canes to offer holiday joy and cheer to your special recipient.",
         "dimensions": "12\"H x 14\"W",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B14-4426_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B14-4426_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B14-4426&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B14-4426&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Centerpieces"
       },
       {
         "name": "Christmas Peace Bouquet",
         "code": "B14-4832",
         "price": 49.95,
         "description": "The Christmas Peace Bouquet captures the elegance of the season at every turn. White roses, red carnations, white stock, green button poms, holly and assorted holiday greens are arranged perfectly in a modern clear square glass vase to create a gift that extends warm wishes for a season of peace and togetherness",
         "dimensions": "14\"H 11\"W",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B14-4832_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B14-4832_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B14-4832&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B14-4832&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Centerpieces"
       },
       {
         "name": "The Season's Glow Centerpiece",
         "code": "B16-4830",
         "price": 59.95,
         "description": "The Season's Glow Centerpiece blooms with winter elegance and holiday enchantment to grace your Christmas celebrations. White LA hybrid lilies, carnations, chrysanthemums and statice are arranged amongst holiday greens and accented with gold pinecones and a gold plaid French wired ribbon for an exquisite look. Arranged to encircle 3 white taper candles, this stunning arrangement will bring a sweet sophistication to your holiday festivities",
         "dimensions": "6\"H x 19\"W",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B16-4830_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B16-4830_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B16-4830&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B16-4830&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Centerpieces"
       },
       {
         "name": "The Winter Wishes Bouquet",
         "code": "B17-4362",
         "price": 64.95,
         "description": "The Winter Wishes Bouquet is a snow-filled display of seasonal elegance. White roses, chrysanthemums, and Asiatic Lilies create winter magic seated in a gold basket and accented with green hypericum berries and a gold plaid ribbon, making this a wish for a season abundant in beauty and togetherness.",
         "dimensions": "9\"H x 11\"W",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B17-4362_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B17-4362_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B17-4362&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B17-4362&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Centerpieces"
       },
       {
         "name": "The Miracle's Light Hanukkah Bouquet",
         "code": "B18-4374",
         "price": 64.95,
         "description": "The Miracle's Light Hanukkah Bouquet celebrates each miraculous moment of this festive and meaningful holiday with its abundance of beautiful blooms. Blue iris creates a splash of color against a backdrop of white roses and white Asiatic lilies accented with lush greens, silver pinecones and blue and silver organza ribbon, gorgeously situated in a clear glass ginger jar vase to create a luminous gift they will treasure throughout the eight days and nights of the Hanukkah season.",
         "dimensions": "11\"H x 9\"W",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B18-4374_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B18-4374_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B18-4374&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B18-4374&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 0,
         "anniversary": 0,
         "love": 0,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Centerpieces"
       },
       {
         "name": "The True Romance Rose Bouquet",
         "code": "B19-4387",
         "price": 69.95,
         "description": "The True Romance Rose Bouquet is the perfect expression of love and passion. A bright burst of color, this bouquet combines red, pink and fuchsia roses, accented with beautiful greens and seated in a clear glass vase, to create a truly romantic representation of your love. ",
         "dimensions": "15\"w x 22\"h",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B19-4387_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B19-4387_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B19-4387&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B19-4387&source_id=aff&affiliateid=2017010398",
         "everyday": 1,
         "birthday": 1,
         "anniversary": 1,
         "love": 1,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Roses"
       },
       {
         "name": "The Autumn Beauty Bouquet",
         "code": "B2-4922",
         "price": 79.95,
         "description": "The Autumn Beauty Bouquet exudes the warmth and magnificence of the harvest season with each sun-kissed bloom. Orange roses are brilliant and bright against rust colored Asiatic lilies, burgundy carnations and mini carnations, red matsumoto asters, red hypericum berries, and a variety of lush greens. Accented with birch branches throughout, this incredible arrangement is seated in a clear glass bubble bowl vase to create an exceptional look your special recipient will love. ",
         "dimensions": "11\"w x 11\"h",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B2-4922_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B2-4922_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B2-4922&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B2-4922&source_id=aff&affiliateid=2017010398",
         "everyday": 1,
         "birthday": 1,
         "anniversary": 1,
         "love": 1,
         "get_well": 1,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Vase Arrangements"
       },
       {
         "name": "The Love-Struck Rose Bouquet",
         "code": "B20-4376",
         "price": 64.95,
         "description": "The Love-Struck Rose Bouquet uses a touch of Cupid's magic this Valentine's Day to usher in romance and sweet love. Bright red roses and hot pink spray roses are artfully arranged amongst lush greens in a clear glass vase tied with a taffeta bi-colored ribbon to create a bouquet of passion and beauty.",
         "dimensions": "10\"w x 14\"h",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B20-4376_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B20-4376_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B20-4376&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B20-4376&source_id=aff&affiliateid=2017010398",
         "everyday": 0,
         "birthday": 1,
         "anniversary": 1,
         "love": 1,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Roses"
       },
       {
         "name": "The Sweet Perfection Bouquet",
         "code": "B20-4798",
         "price": 49.95,
         "description": "The Sweet Perfection Bouquet is an eye-catching way to capture their attention. Rich red roses and carnations are beautifully set amongst baby's breath and lush greens in a classic clear glass vase to create a sweet sentiment of love and affection. ",
         "dimensions": "10\"w x 15\"h",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B20-4798_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B20-4798_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B20-4798&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B20-4798&source_id=aff&affiliateid=2017010398",
         "everyday": 1,
         "birthday": 1,
         "anniversary": 1,
         "love": 1,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 1,
         "sympathy": 0,
         "category": "Vase Arrangements"
       },
       {
         "name": "The Love Wonder Bouquet",
         "code": "B22-4801",
         "price": 89.95,
         "description": "The Love Wonder Bouquet bursts with the beauty and magic of love's finest moments. Brilliant red roses are brought together with fuchsia tulips and lush greens in a classic clear glass vase to create a bouquet rich in romance and sweet sentiments. ",
         "dimensions": "11\"w x 15\"h",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B22-4801_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B22-4801_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B22-4801&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B22-4801&source_id=aff&affiliateid=2017010398",
         "everyday": 1,
         "birthday": 1,
         "anniversary": 1,
         "love": 1,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Vase Arrangements"
       },
       {
         "name": "The Red Romance Rose Bouquet",
         "code": "B23-4375",
         "price": 69.95,
         "description": "The Red Romance Rose Bouquet will dazzle your special recipient with its expression of love and beauty this coming Valentine's Day. Rich red roses and spray roses are gorgeously arranged in a clear glass vase, accented with a lovely mix of greens, to create a bouquet bursting with romantic intentions. ",
         "dimensions": "10\"w x 13\"h",
         "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B23-4375_t1.jpg",
         "picture_url_l": "http://www.floristone.com/flowers/products/B23-4375_d1.jpg",
         "page_url": "http://www.floristone.com/detail.cfm?dcode=B23-4375&source_id=aff&affiliateid=2017010398",
         "cart_url": "http://www.floristone.com/cart.cfm?dcode=B23-4375&source_id=aff&affiliateid=2017010398",
         "everyday": 1,
         "birthday": 1,
         "anniversary": 1,
         "love": 1,
         "get_well": 0,
         "new_baby": 0,
         "thank_you": 0,
         "sympathy": 0,
         "category": "Roses"
       }])
     })
    .then(() => {
      return knex.raw(
        "SELECT setval('flowers_id_seq', (SELECT MAX(id) FROM flowers));"
      );
    });
};
