'use strict';

/* eslint max-len: ["error", 1000]*/
exports.seed = function(knex) {
  return knex('flowers').del()
    .then(() => {
      return knex('flowers').insert([{
        "name": "Anniversary Bouquet",
        "code": "AVB",
        "price": 54.95,
        "description": "The Anniversary Bouquet is a gorgeous way to celebrate your sweet affection for the love of your life on your special day. Showcasing rich red roses, brilliant pink Asiatic lilies, pale pink stock and a variety of lush greens, this beautiful bouquet is presented in a clear t glass vase for a classic look of sophistication and elegance.",
        "dimensions": "13\"w x 15\"h",
        "picture_url_s": "http://www.floristone.com/flowers/thumbnails/AVB_t1.jpg",
        "picture_url_l": "http://www.floristone.com/flowers/products/AVB_d1.jpg",
        "page_url": "http://www.floristone.com/detail.cfm?dcode=AVB&source_id=aff&affiliateid=2017010398",
        "cart_url": "http://www.floristone.com/cart.cfm?dcode=AVB&source_id=aff&affiliateid=2017010398",
        "everyday": "0",
        "birthday": "0",
        "anniversary": "1",
        "love": "1",
        "get_well": "0",
        "new_baby": "0",
        "thank_you": "0",
        "sympathy": "0",
        "category": "Vase Arrangements"
      }, {
        "name": "The Holiday Happiness Bouquet",
        "code": "B10-4355",
        "price": 47.95,
        "description": "The Holiday Happiness Bouquet",
        "dimensions": "13\"H x 10\"W",
        "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B10-4355_t1.jpg",
        "picture_url_l": "http://www.floristone.com/flowers/products/B10-4355_d1.jpg",
        "page_url": "http://www.floristone.com/detail.cfm?dcode=B10-4355&source_id=aff&affiliateid=2017010398",
        "cart_url": "http://www.floristone.com/cart.cfm?dcode=B10-4355&source_id=aff&affiliateid=2017010398",
        "everyday": "0",
        "birthday": "0",
        "anniversary": "0",
        "love": "0",
        "get_well": "0",
        "new_baby": "0",
        "thank_you": "0",
        "sympathy": "0",
        "category": "Centerpieces"
      }, {
        "name": "Celebration of the Season Centerpiece",
        "code": "B10-4368",
        "price": 74.95,
        "description": "The Celebration of the Season Centerpiece is a grand display of holiday elegance. Red roses and spray roses pop against a backdrop of assorted holiday greens and variegated holly that beautifully encircle three red taper candles. Accented with gold pinecones and gold metallic brocade ribbon this centerpiece creates a warm and enchanting glow to benefit their holiday festivities.",
        "dimensions": "7\"H x 14\"W",
        "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B10-4368_t1.jpg",
        "picture_url_l": "http://www.floristone.com/flowers/products/B10-4368_d1.jpg",
        "page_url": "http://www.floristone.com/detail.cfm?dcode=B10-4368&source_id=aff&affiliateid=2017010398",
        "cart_url": "http://www.floristone.com/cart.cfm?dcode=B10-4368&source_id=aff&affiliateid=2017010398",
        "everyday": "0",
        "birthday": "0",
        "anniversary": "0",
        "love": "0",
        "get_well": "0",
        "new_baby": "0",
        "thank_you": "0",
        "sympathy": "0",
        "category": "Centerpieces"
      }, {
        "name": "The Spirit of the Season Bouquet",
        "code": "B10-4787",
        "price": 49.95,
        "description": "The Spirit of the Season Bouquet bursts with beauty and cheer to dazzle your special recipient with its holiday beauty. Brilliant red spray roses and mini carnations are brought together with burgundy mini carnations, red hypericum berries and assorted holiday greens in a clear glass vase accented with a thick red designer ribbon to create a special sentiment of seasonal wishes and caring kindness",
        "dimensions": "14\"H x 9\"W",
        "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B10-4787_t1.jpg",
        "picture_url_l": "http://www.floristone.com/flowers/products/B10-4787_d1.jpg",
        "page_url": "http://www.floristone.com/detail.cfm?dcode=B10-4787&source_id=aff&affiliateid=2017010398",
        "cart_url": "http://www.floristone.com/cart.cfm?dcode=B10-4787&source_id=aff&affiliateid=2017010398",
        "everyday": "0",
        "birthday": "0",
        "anniversary": "0",
        "love": "0",
        "get_well": "0",
        "new_baby": "0",
        "thank_you": "0",
        "sympathy": "0",
        "category": "Centerpieces"
      }, {
        "name": "The Winter Elegance Bouquet",
        "code": "B12-4421",
        "price": 69.95,
        "description": "The Winter Elegance Bouquet offers warm wishes and bright sentiments for a wonderful holiday season! Rich red roses and peppermint carnations are delicately arranged amongst holiday greens to create a festive display.Arriving in a clear glass bubble bowl and accented with a red and white plaid ribbon, this arrangement is full of seasonal sophistication.",
        "dimensions": "7\"H x 14\"W",
        "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B12-4421_t1.jpg",
        "picture_url_l": "http://www.floristone.com/flowers/products/B12-4421_d1.jpg",
        "page_url": "http://www.floristone.com/detail.cfm?dcode=B12-4421&source_id=aff&affiliateid=2017010398",
        "cart_url": "http://www.floristone.com/cart.cfm?dcode=B12-4421&source_id=aff&affiliateid=2017010398",
        "everyday": "0",
        "birthday": "0",
        "anniversary": "0",
        "love": "0",
        "get_well": "0",
        "new_baby": "0",
        "thank_you": "0",
        "sympathy": "0",
        "category": "Centerpieces"
      }, {
        "name": " Red Poinsettia Basket (Small)  ",
        "code": "B13-3601",
        "price": 49.95,
        "description": "The traditional holiday blooming plant, a Christmas Poinsettia, with its dark leaves and deep red flowers is the perfect gift for family and friends.",
        "dimensions": "6\" pot",
        "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B11-3601_t1.jpg",
        "picture_url_l": "http://www.floristone.com/flowers/products/B11-3601_d1.jpg",
        "page_url": "http://www.floristone.com/detail.cfm?dcode=B13-3601&source_id=aff&affiliateid=2017010398",
        "cart_url": "http://www.floristone.com/cart.cfm?dcode=B13-3601&source_id=aff&affiliateid=2017010398",
        "everyday": "0",
        "birthday": "0",
        "anniversary": "0",
        "love": "0",
        "get_well": "0",
        "new_baby": "0",
        "thank_you": "0",
        "sympathy": "0",
        "category": "Plants"
      }, {
        "name": " Red Poinsettia Basket (Large)  ",
        "code": "B13-3602",
        "price": 74.95,
        "description": "The traditional holiday blooming plant, a Christmas Poinsettia, with its dark leaves and deep red flowers is the perfect gift for family and friends.",
        "dimensions": "8\" pot",
        "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B11-3602_t1.jpg",
        "picture_url_l": "http://www.floristone.com/flowers/products/B11-3602_d1.jpg",
        "page_url": "http://www.floristone.com/detail.cfm?dcode=B13-3602&source_id=aff&affiliateid=2017010398",
        "cart_url": "http://www.floristone.com/cart.cfm?dcode=B13-3602&source_id=aff&affiliateid=2017010398",
        "everyday": "0",
        "birthday": "0",
        "anniversary": "0",
        "love": "0",
        "get_well": "0",
        "new_baby": "0",
        "thank_you": "0",
        "sympathy": "0",
        "category": "Plants"
      }, {
        "name": "The Holiday Enchantment Bouquet",
        "code": "B13-4834",
        "price": 54.95,
        "description": "The Holiday Enchantment Bouquet is blooming with bright seasonal cheer to bring Christmas joy to your special recipient. Rich red roses are surrounded by white Peruvian lilies, variegated holly and assorted holiday greens perfectly arranged in a clear glass vase tied at the neck with a candy cane striped ribbon to create a fantastic holiday look.",
        "dimensions": "16\"H x13\"W",
        "picture_url_s": "http://www.floristone.com/flowers/thumbnails/B13-4834_t1.jpg",
        "picture_url_l": "http://www.floristone.com/flowers/products/B13-4834_d1.jpg",
        "page_url": "http://www.floristone.com/detail.cfm?dcode=B13-4834&source_id=aff&affiliateid=2017010398",
        "cart_url": "http://www.floristone.com/cart.cfm?dcode=B13-4834&source_id=aff&affiliateid=2017010398",
        "everyday": "0",
        "birthday": "0",
        "anniversary": "0",
        "love": "0",
        "get_well": "0",
        "new_baby": "0",
        "thank_you": "0",
        "sympathy": "0",
        "category": "Centerpieces"
      }]);
    })
    .then(() => {
      return knex.raw(
        "SELECT setval('flowers_id_seq', (SELECT MAX(id) FROM flowers));"
      );
    });
};
